---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

##Read some data
read in the litters dataset
```{r}
litters_df = read.csv("./data/FAS_litters.csv")
#update the name of some variables#
litters_df = janitor::clean_names(litters_df)

```
## take a look at the data
```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
```
```{r}
skimr::skim(litters_df)
```


##options to read_csv
```{r}
litters_df = 
    read_csv(file = "./data/FAS_litters.csv",
    skip = 10, col_names = FALSE)
```
check out `?read_csv` for more information


## read excel file

```{r}
library
mlb_df = read_excel("./data/mlb11.xlsx", rang= "A1:f7")
mlb_df
```

## read sas file
```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```


## Comparison with Base R
what about `read_csv` ...?
```{r}
pups_base = read.csv("./data/FAS_pups.csv")
pups_readr = read_csv("./data/FAS_pups.csv")

View(pups_base)
View(pups_readr)

pups_base
pups_readr
```



