---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
```

```{r}

litters_df = 
    read_csv("./data/FAS_litters.csv", na = c("NA", ".", ""))
litters_df = 
    janitor::clean_names(litters_df)

pups_df = 
    read_csv("./data/FAS_pups.csv", na = c("NA", "."), skip = 3)
```
## `select`
Choose some columns not others
```{r}
select(litters_df, group, litter_number)
```
```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```
```{r delete litter_number}
select(litters_df, -litter_number)
```
renaming
```{r}
select(litters_df, GROUP=group, LITTER_NUMBER=litter_number)
```
```{r}
rename(litters_df, GROUP=group, LITTER_NUMBER=litter_number)
```
```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```
```{r}
relocate(litters_df, litter_number)
```


## `filter`

```{r}
filter(litters_df, gd_of_birth == 20)
```
```{r}
filter(litters_df, gd_of_birth != 20)
```
```{r}
filter(litters_df, group=="Mod8")
```

```{r}
filter(litters_df, group %in% c("Con8", "Mod8"))
```
## `mutate`
```{r}
mutate(litters_df,
  wt_gain = gd18_weight-gd_of_birth,
  group = str_to_lower(group))
```

## `arrange`

```{r}
arrange(litters_df, pups_born_alive)


```
## pipe `%/%`

```{r}

litters_dataraw = read.csv("./data/FAS_litters.csv")
litters_clean = janitor::clean_names(litters_dataraw)
litters_select= select(litters_clean, -pups_survive)
litters_mutate <= (litters_select, wt_gain=gd18_weight-gd0_weight)
litters_dropmissing=drop_na(litters_select)
```


```{r pipe}
litters_df=
  read.csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
select(-pups_survive) %>% 
  mutate=(wt_gain= GD18.weight - GD0.weight) 
```
  select(-pups_survive) %>% 
  mutate=(wt_gain= gd18_weight - gd0_weight) %>% 
  drop_na(wt_gain)



