---
title: "tidy_data"
output: github_document
date: "2025-09-23"
---

```{r setup, include=FALSE}
library(tidyverse)
```

## `pivot_longer data`

load pulse data

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
pulse_df
```
wide format to long format...

```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi")
```

rewrite, combine and add a mutate 
```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi"
    ) %>% 
    relocate(id, visit) %>% 
    mutate(visit = recode(visit, "bdi_score_bl" = "bdi_score_00m"),
    visit = factor(visit))
```

## `pivot wider`


make up some data
```{r}
analysis_result =
  tibble(
    group= c("treatment", "treatment", "placebo", "placebo"),
    time=c("pre", "post", "pre", "post"),
    mean=c(4,8,3.5,4)
  )

analysis_result %>% 
pivot_wider(
  names_from = "time", 
  values_from = "mean")

```


## binding rows

using the lord of rings data.
first step: import each table.

```{r}
fellowship_ring=
  readxl::read_excel("data/LotR_Words.xlsx", range = "B3:D6") %>% 
mutate(movie="Fellowship of the ring")

two_towers=
  readxl::read_excel("data/LotR_Words.xlsx", range = "F3:H6") %>% 
mutate(movie="two_towers")

return_king=
  readxl::read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>% 
mutate(movie="return_king")
```

bind all rows together

```{r}
lotr_tidy=
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
    
  )
```












